export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        secondary: '#595799',
        tertiary: '#356574',
        'inverse-primary': '#ffb695',
        'on-surface-variant': '#56423a',
        'on-secondary-fixed': '#141052',
        surface: '#f9f9f9',
        'text-dark': '#1A1A2E',
        'surface-tint': '#9f420c',
        'on-primary': '#ffffff',
        'surface-container-low': '#f3f3f4',
        'on-background': '#1a1c1c',
        'amber-accent': '#E8A830',
        'on-secondary-fixed-variant': '#413f80',
        'on-tertiary-fixed-variant': '#194d5c',
        'on-secondary': '#ffffff',
        'primary-fixed': '#ffdbcc',
        'inverse-surface': '#2f3131',
        'on-secondary-container': '#454484',
        'on-tertiary-fixed': '#001f28',
        'on-tertiary': '#ffffff',
        'primary-container': '#f4824a',
        'star-yellow': '#FFC107',
        outline: '#8a7268',
        'tertiary-container': '#79a8b9',
        'outline-variant': '#ddc1b5',
        'surface-bright': '#f9f9f9',
        background: '#f9f9f9',
        'on-primary-fixed-variant': '#7c2e00',
        'secondary-container': '#b6b4fe',
        error: '#ba1a1a',
        'surface-dim': '#dadada',
        'primary-fixed-dim': '#ffb695',
        'tertiary-fixed-dim': '#9ecee0',
        'ghost-paw': '#E0E0EE',
        'tertiary-fixed': '#baeafc',
        'surface-container': '#eeeeee',
        'secondary-fixed': '#e2dfff',
        'secondary-fixed-dim': '#c3c0ff',
        'on-tertiary-container': '#013d4c',
        primary: '#9f420c',
        'inverse-on-surface': '#f0f1f1',
        'error-container': '#ffdad6',
        'text-muted': '#6B6B8A',
        'surface-variant': '#e2e2e2',
        'border-light': '#E8E8F0',
        'on-primary-fixed': '#351000',
        'on-error-container': '#93000a',
        'on-primary-container': '#632400',
        'surface-container-highest': '#e2e2e2',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e8e8e8',
        'on-error': '#ffffff',
        'on-surface': '#1a1c1c',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-md': '1rem',
        'stack-lg': '2.5rem',
        'stack-sm': '0.5rem',
        'section-gap': '6rem',
        'container-max': '1200px',
        gutter: '1.5rem',
      },
      fontFamily: {
        // Display/Logo - Rounded, playful, perfect for pet shop branding
        'hero-display': ['"Fredoka One"', 'cursive'],
        // Section headings - Friendly rounded sans-serif
        'h2-section': ['"Baloo 2"', 'cursive'],
        // Card headings - Clean but friendly
        'h3-card': ['"Nunito"', 'sans-serif'],
        // UI Labels/Buttons - Modern rounded
        'ui-label': ['"Quicksand"', 'sans-serif'],
        // Prices - Bold, clear
        'price-lg': ['"Nunito"', 'sans-serif'],
        // Body text - Highly readable, friendly
        'body-main': ['"Nunito"', 'sans-serif'],
        'body-small': ['"Nunito"', 'sans-serif'],
      },
      fontSize: {
        'hero-display': ['72px', { lineHeight: '1.1', letterSpacing: '0.02em', fontWeight: '400' }],
        'h2-section': ['32px', { lineHeight: '1.3', fontWeight: '700' }],
        'h3-card': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'ui-label': ['15px', { lineHeight: '1.2', fontWeight: '600' }],
        'price-lg': ['20px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-main': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-small': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
      },
      keyframes: {
        rotate: {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
        fadeUp: {
          from: { opacity: '0', transform: 'translateY(24px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'stamp-rotate': 'rotate 15s linear infinite',
        'fade-up': 'fadeUp 0.5s ease both',
      },
    },
  },
  plugins: [],
};
